repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]

      - id: no-commit-to-branch
        name: "don't commit to branch"
        entry: no-commit-to-branch
        language: python
        pass_filenames: false
        always_run: true

      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system

      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        types: [toml]

      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        language: system
        types: [yaml]

      - id: detect-private-key
        name: detect private key
        description: detects the presence of private keys.
        entry: detect-private-key
        language: python
        types: [text]

      - id: black-jupyter
        name: Black for Jupyter
        entry: black
        language: system
        types: [jupyter]
        require_serial: true

      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        'types_or': [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: '2.9.2'

      - id: poetry-check
        name: poetry-check
        description: run poetry check to validate config
        entry: poetry check
        language: python
        pass_filenames: false
        files: ^(.*/)?pyproject.toml$

      - id: poetry-export
        name: poetry-export
        description: run poetry export to sync lock file with requirements.txt
        entry: poetry export
        language: python
        pass_filenames: false
        files: ^(.*/)?poetry\.lock$
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
